spring:
  application:
    name: Task_DB_01
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12341234
  flyway:
    enabled: true
    clean-on-validation-error: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 12341234
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftlh
logging:
  level:
    org:
      flywaydb: DEBUG
  file:
    name: logs/spring.log
management:
  endpoints:
    web:
      exposure:
        include: "*"