<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit ordered product ${orderItem.product.productId} - Auto Parts Store</title>
    <link rel="stylesheet" href="/styles/styles.css">
</head>

<body>
<header>
    <h1>Edit ordered product ${orderItem.product.productId}</h1>
    <nav>
        <a href="/">Home</a>
    </nav>
</header>
</body>
