<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Auto Parts Store</title>
    <link rel="stylesheet" href="/styles/styles.css">
</head>

<body>
<header>
    <h1>Welcome to Auto Parts Store</h1>
    <nav>
        <a href="/products">Products</a>
        <a href="/customers">Customers</a>
        <a href="/statistics_of_orders">Statistics of orders</a>
    </nav>
</header>

<main>
    <h2>Discover a wide range of auto parts at competitive prices!</h2>
    <p>Your one-stop shop for all your automotive needs. Explore our product catalog to find the best parts for your
        vehicle.</p>
</main>

<footer>
    <p>&copy; 2024 Auto Parts Store</p>
</footer>
</body>
</html>
